lldp_interfaces:
-   name: GigabitEthernet1
    receive: true
    transmit: true
-   name: GigabitEthernet2
    receive: true
    transmit: true
-   name: GigabitEthernet3
    receive: true
    transmit: true
